import { getSlider } from "@/actions/slider/sliderAction";
import { SliderTable } from "@/components/dashboard/slider/sliderTable";
import { Button } from "@/components/ui/button";
import { Metadata } from "next";
import Link from "next/link";

export const metadata: Metadata = {
    title: "Grameen Shop test",
    description: "Generated by Grameen Shop",
};

export default async function Slider() {


    const data = await getSlider();


    return (
        <div>
            <div className="border mb-4 p-4 rounded-xl flex justify-between">
                <h2 className="text-xl font-semibold">Slider list</h2>

                <Button asChild>
                    <Link href="/dashboard/slider/create">Create</Link>
                </Button>
            </div>
            <SliderTable data={data} />
        </div>
    )
}
